### ISSUE TITLE
Chapter 3, in cifar10, first dropout must be after Flatten, right? I think dropout use in fully connected block, not in Convolution block!

### ISSUE THREAD

**Issue by hmh10098** [moelgendy/grokking_deep_learning_for_computer_vision#30]
![image](https://user-images.githubusercontent.com/65597836/147338314-6859d1cc-dbeb-4e73-834d-8ca60975b4fa.png)
This is my accuracy when i push dropout(0.3) after Flatten, not Convolution!

**Comment by Mel65** [comment]
Are none of these questions being answered?

**Comment by moelgendy** [comment]
@hmh10098 dropout layers can be added after the Flattened layer as well. Seems that you are getting better results for this project.
